config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'notes#index'
  get 'search' => 'notes#search'
  get 'category_search/:id' => 'notes#category_search'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:following, :followers, :following_article] do
    member do
      get :following, :followers, :following_article
    end
  end
  resources :notes, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :update, :destroy]
  end
  get 'mypages/pv' => 'mypages#pv'
  get 'mypages/favorite' => 'mypages#favorite'
  resources :mypages, only: [:show]
  resources :relationships, only: [:create, :destroy]
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # impressionist actions: [:show]
  def index
    @articles = Article.includes(:user).all.order("created_at DESC")
    @slidepics = Article.last(3)
    @tags = ActsAsTaggableOn::Tag.most_used(7)
    # @rank = Article.find(Impression.group(:impressionable_id).order('count_all desc').limit(5).count.keys)

    # その日のランキング作成アルゴリズム部分
    daily_pageviews = Hash.new
    today = Date.today.to_s
    @articles.each do |article|
      daily_pageviews[article.id] = REDIS.get "posts/daily/#{today}/#{article.id}"
    end
    daily_pageviews_ranking = daily_pageviews.sort{|a, b| b[1] <=> a[1]}
    top3_articles = daily_pageviews_ranking[0..4]
    @rank = []
    top3_articles.each{|key,val|
      @rank << Article.find(key)
    }
  end

  def show
    @article = Article.includes(:user).find(params[:id])
    @fav_count = Favorite.where(article_id: params[:id])
    # @impressions = Impression.where(impressionable_id: params[:id])
    @fav_yet = Favorite.where(user_id: current_user.id).where(article_id: params[:id]) if user_signed_in?
    @tags = @article.tag_list

    # ビュー数をカウントします
    REDIS.incr "posts/daily/#{Date.today.to_s}/#{@article.id}"

    # 各記事のビュー数を表示します
    view_counts = 0
    selected_articles = REDIS.keys "*/#{@article.id}*"
    selected_articles.each do |selected_article|
       view_count = REDIS.get "#{selected_article}"
       view_counts += view_count.to_i
    end
    @view_counts = view_counts
  end

  def new
    @article = Article.new
    @categories = Category.all
    @tags = ActsAsTaggableOn::Tag.most_used(7)
  end

  def create
    article = Article.new(create_params)
    if article.save
      redirect_to notes_path
    else
      redirect_to new_note_path
    end
  end

  def search
    @articles = Article.where('title LIKE(?)',"%#{params[:title]}%").order("created_at DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def category_search
    @articles = Article.where(category_id: params[:id]).order("created_at DESC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def create_params
    params.require(:article).permit(:title, :text, :thumbnail, :tag_list, :category_id).merge(user_id: current_user.id)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_article.html.haml
%div.article
  = link_to note_path(article.id) do
    %img.article__image{src: article.thumbnail }
  %div.article__texts
    = link_to note_path(article.id), class: 'article__texts__title-link' do
      %p.article__texts__title= article.title
    %div.article__texts__detail
      = strip_tags(article.text).gsub(/(\r\n|\r|\n)/, '').gsub(/(\xc2\xa0|\s)+/, '')
    %img.article__texts__avatar{src: article.user.avatar }
    = link_to mypage_path(article.user.id) do
      %p.article__texts__user-name= article.user.name
    %p.article__texts__date= article.created_at.strftime('%Y.%m.%d')

app/views/notes/index.html.haml
%div.slide
  -@slidepics.each do |pic|
    %p.slide_title
    %img.slide__image{src: pic.thumbnail }

%p.todays-article 本日の記事

%div.body
  %div.body__left
    = render partial: "article", collection: @articles

  %div.body__right
    %div.body__right__categories
      %p カテゴリ一覧
      %div.body__right__categories__category
        %div.fa-box
          =link_to root_path do
            %i.fa.fa-home.fa-2x
        =link_to root_path do
          %p トップ
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-suitcase.fa-2x
        %p ビジネス
        %input{type:'hidden', value: 1}
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-book.fa-2x
        %p 本
        %input{type:'hidden', value: 2}
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-bicycle.fa-2x
        %p ライフスタイル
        %input{type:'hidden', value: 3}
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-black-tie.fa-2x
        %p メンズファッション
        %input{type:'hidden', value: 4}
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-calendar-check-o.fa-2x
        %p イベント
        %input{type:'hidden', value: 5}
      %div.body__right__categories__category
        %div.fa-box
          %i.fa.fa-microphone.fa-2x
        %p インタビュー
        %input{type:'hidden', value: 6}

    %div.body__right__famouses
      %p.body__right__famouses__title 記事ランキング
      %p.body__right__famouses__time= Time.now.strftime('%m月%d日') + 'にアクセスが多かった記事はこちら！'
      - @rank.each.with_index(1) do |rank, i|
        %div.body__right__famouses__box
          %p.body__right__famouses__box__rank= "第#{i}位"
          = link_to note_path(rank.id) do
            %img.body__right__famouses__box__article-thumbnail{src: rank.thumbnail }
          = link_to note_path(rank.id), class: 'body__left__famouses__box__article-title-link' do
            %p.body__right__famouses__box__article-title= rank.title



    %div.body__right__news
      %p 新着特集

    %div.body__right__keywords
      %p 話題のキーワード
      %div.body__right__keywords__tags-box
        - @tags.each do |tag|
          %div.body__right__keywords__tags-box__tag-box
            %i.fa.fa-tag
            %p.tag= tag.name

app/views/notes/new.html.haml
%p.page-title 記事作成

%div.post-article
  = form_for @article, url:{ controller: :notes, action: :create}, html:{class: 'post-article__form', :multipart => true } do |f|
    = f.text_field :title, class: 'post-article__form__title', placeholder: '記事タイトル（４８字以内）', maxlength: 48
    = f.cktext_area :text, class: 'post-article__form__text'

    %div.tag-form
      %p.tag-form__title タグ
      %div.tag-form__left
        = text_field_tag 'article[tag_list]', @article.tag_list.join(','), class: 'tag-form__left__text',placeholder: '1~100文字で入力してください'
        %p タグが複数ある場合はコンマで区切ってください
        %ul.lists
      %div.tag-form__right
        %p よく使われるタグ
        %div.tag-library
          - @tags.each do |tag|
            %div.tag-library__tag-box
              %i.fa.fa-tag
              %p.tag= tag.name

    %div.pic-form
      %p.pic-form__title サムネイル画像
      %p.pic-form__notice 画像の選択
      %div.icon-box
        %div.icon-box__select
          %label{for: "thumbnail", class: "fa fa-picture-o fa-5x comment-form__icon" }
            = f.file_field :thumbnail, id: 'thumbnail', style: 'display: none;', class: "file"
          %p.icon-box__notice +他の画像を選択

    %div.send-form
      %select{name: 'article[category_id]', class: 'select-form'}
        %option{value: 0 } カテゴリを選択（必須）
        - @categories.each do |category|
          %option{value: category.id }= category.name
      %input.post-article__form__button{type: "submit", value: "Sent"}/

app/views/notes/show.html.haml
%div.show-inner
  %div.show-inner__title-box
    %h1.show-inner__title-box__title= @article.title
  %div.show-inner__SNS-box
    %div.show-inner__SNS-box__fav-count
      %div.show-inner__SNS-box__fav-count__size= @fav_count.length
      - if user_signed_in?
        %div.show-inner__SNS-box__fav-count__wrap
          - if @fav_yet.exists?
            %input.show-inner__SNS-box__fav-count__wrap__button{type: "submit", value: "お気に入り済み"}
          - else
            %input.show-inner__SNS-box__fav-count__wrap__button{type: "submit", value: "お気に入り"}
        - @fav_yet.each do |yet|
          %input.show-inner__SNS-box__fav-count__already{type: "hidden", value: yet.id}
      - else
        = link_to new_user_session_path do
          %input.show-inner__SNS-box__fav-count__button-not-sign-in{type: "submit", value: "お気に入り"}

  %div.show-inner__info-space
    %div.show-inner__info-space__box
      %i.fa.fa-calendar
      %div.show-inner__info-box__date= @article.created_at.strftime('%Y年%m月%d日')
    %div.show-inner__info-space__box
      %i.fa.fa-eye
      %div.show-inner__info-box__view= @view_counts
    %div.show-inner__info-space__box
      %i.fa.fa-star-o
      %div.show-inner__info-box__fav= @fav_count.length
    %div.show-inner__info-space__user-box
      = link_to mypage_path(@article.user), class: "show-inner__info-space__user-box__writer-link" do
        %p.show-inner__info-space__user-box__writer= @article.user.name
    %div.show-inner__info-space__user-box
      %img.show-inner__info-space__user-box__avatar{src: "#{@article.user.avatar}"}

  %img.show-inner__image{src: @article.thumbnail }
  != @article.text