config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'notes#index'
  get 'search' => 'notes#search'
  get 'category_search/:id' => 'notes#category_search'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users, only: [:following, :followers, :following_article] do
    member do
      get :following, :followers, :following_article
    end
  end
  resources :notes, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :update, :destroy]
  end
  get 'mypages/pv' => 'mypages#pv'
  get 'mypages/favorite' => 'mypages#favorite'
  resources :mypages, only: [:show]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UNote
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body

    %div.header
      %div.header__title
        = link_to root_path do
          %p.header__title__logo U-NOTE
        = link_to new_user_session_path do
          %p.header__title__copy 仕事を楽しく、毎日をかっこ良く
      - if user_signed_in?
        %div.header__search
          %form
            %input{class: "header__search__text",type: "text", name: "search", placeholder: "知りたいことを入力"}
        %div.fa-icons
          = link_to new_note_path do
            %i.fa.fa-pencil-square-o.fa-2x
          = link_to mypage_path(current_user) do
            %i.fa.fa-archive.fa-2x
        %div.menu
          %img.menu__avatar{src: current_user.avatar}
          %ul.menu__user
            = current_user.name
            = link_to mypage_path(current_user), class: "menu__user__lists-link" do
              %li.menu__user__lists マイページ
            = link_to edit_user_registration_path(current_user), class: "menu__user__lists-link" do
              %li.menu__user__lists プロフィール設定
            = link_to destroy_user_session_path, class: "menu__user__lists-link", method: :delete do
              %li.menu__user__lists ログアウト


    = yield